# Generated by Django 4.0.2 on 2022-02-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('number_of_questions', models.PositiveSmallIntegerField()),
                ('difficulty', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Quize',
            },
        ),
    ]
