# Generated by Django 4.0.2 on 2022-02-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0003_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['quiz_id'], 'verbose_name_plural': 'Quizes'},
        ),
    ]
